---
- hosts: jenkins
  become: true
  tasks:
    - name: Add Jenkins package repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present
        key_url: 'https://pkg.jenkins.io/debian/jenkins.io.key'
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
    - name: Wait for Jenkins to start
      wait_for:
        port: 8080
        state: started
        delay: 60
        timeout: 360
    - name: Get Jenkins initial admin password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
    - name: Install default plugins
      uri:
        url: "http://localhost:8080/pluginManager/installNecessaryPlugins"
        method: POST
        body: "{{ item }}"
        status_code: 302
      with_items:
        - "git:latest"
        - "github:latest"
        - "gradle:latest"
        - "pipeline-stage-view:latest"
        - "ssh-slaves:latest"
    - name: Create initial admin user
      uri:
        url: "http://localhost:8080/securityRealm/createAccount"
        method: POST
        body: "username=admin&password1={{ admin_password }}&password2={{ admin_password }}"
        status_code: 200
      vars:
        admin_password: "{{ jenkins_password.stdout }}"
    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted

