---
- hosts: load-balancer
  become: true
  tasks:
    - name: Update apt
      apt:
        update_cache: yes
        cache_valid_time: 86400
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Create nginx configuration directory
      file:
        path: /etc/nginx/conf.d
        state: directory
    - name: Send nginx load balancer configuration
      template:
        src: load_balancer.conf.j2
        dest: /etc/nginx/conf.d/load_balancer.conf
    - name: Restart nginx
      service: name=nginx state=restarted enabled=yes
