---
#- hosts: nfs-server
#  become: yes
#  roles:
#    - nfs-server

- hosts: mariadb
  become: yes
  roles:
    - mariadb

- hosts: nfs-client
  become: yes
  roles:
    - nfs-client

- hosts: load-balancer
  become: yes
  roles:
    - load-balancer

- hosts: jenkins
  become: yes
  roles:
    - jenkins

- hosts: jenkins-agent
  become: yes
  roles:
    - jenkins-agent
