---
- hosts: nfs-server
  become: yes
  roles:
    - nfs-server

- hosts: mariadb
  become: yes
  roles:
    - mariadb

- hosts: nfs-client1:nfs-client2
  become: yes
  vars:
    mariadb_ip: 10.26.0.191
  roles:
    - nfs-client

- hosts: nfs-client1
  become: yes
  roles:
    - gogs-launch
- hosts: nfs-client2
  become: yes
  roles:
    - gogs-launch
- hosts: load-balancer
  become: yes
  vars:
    app1_ip: 10.26.0.193
    app2_ip: 10.26.0.195
  roles:
    - load-balancer

- hosts: jenkins
  become: yes
  roles:
    - jenkins

