---
#- hosts: nfs-server
#  become: yes
#  roles:
#    - nfs-server

- hosts: mariadb
  become: yes
  roles:
    - mariadb

- hosts: nfs-client
  become: yes
  vars:
    mariadb_ip: 10.26.0.168
  roles:
    - nfs-client

- hosts: load-balancer
  become: yes
  vars:
    app1_ip: 10.26.0.57
    app2_ip: 10.26.0.71
  roles:
    - load-balancer

- hosts: jenkins
  become: yes
  roles:
    - jenkins

