---
- hosts: nfs-server
  become: yes
  roles:
    - nfs-server

- hosts: mariadb
  become: yes
  roles:
    - mariadb

- hosts: nfs-client
  become: yes
  vars:
    mariadb_ip: 10.26.0.185
  roles:
    - nfs-client

- hosts: load-balancer
  become: yes
  vars:
    app1_ip: 10.26.0.183
    app2_ip: 10.26.0.184
  roles:
    - load-balancer

- hosts: jenkins
  become: yes
  roles:
    - jenkins

