---
    - name: update apt
      apt:
        update_cache: yes
    - name: install jdk
      apt:
        name: default-jdk
        state: present
    - name: install git
      apt:
        name: git
        state: present


