---
    - name: Update yum
      yum:
        update_cache: yes
    - name: Install pip
      yum:
        name: python3-pip
        state: present
    - name: install setuptools
      yum:
        name: python3-setuptools
        state: latest
    - name: Install PyMySQL
      pip:
        name: PyMySQL
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Install MariaDB
      yum:
        name: mariadb-server
        state: present
    - name: Start MariaDB
      service:
        name: mariadb
        state: started
    - name: Create MariaDb database
      mysql_db:
        name: "{{ mariadb_database }}"
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: Create MariaDB user
      mysql_user:
        name: "{{ mariadb_user }}"
        password: "{{ mariadb_password }}"
        host: "%"
        priv: "*.*:ALL"
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: Grant all privileges to MariaDB user
      mysql_user:
        name: "{{ mariadb_user }}"
        priv: "{{ mariadb_database }}.*:ALL"
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: Set MariaDB bind address
      lineinfile:
        path: /etc/my.cnf.d/server.cnf
        line: "bind-address=0.0.0.0"
        state: present
    - name: enable access to port 3306
      shell: firewall-cmd --zone=public --add-port=3306/tpc --permanent
    - name: reload firewall
      shell: firewall-cmd --reload
    - name: Restart mysql
      service:
        name: mariadb
        state: restarted

