---
    - name: Update apt
      apt:
        update_cache: yes
        cache_valid_time: 86400
    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install PyMySQL
      pip:
        name: pymysql
        state: present

    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present
    - name: Start MariaDB
      service:
        name: mysql
        state: started
    - name: Create MariaDb database
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ mariadb_database }}"
        state: present
    - name: Create MariaDB user
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ mariadb_user }}"
        password: "{{ mariadb_password }}"
        host: "%"
        priv: "*.*:ALL"
        state: present
    - name: Grant all privileges to MariaDB user
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ mariadb_user }}"
        priv: "{{ mariadb_database }}.*:ALL"
        state: present
    - name: Set MariaDB bind address
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: "bind-address.*"
        line: "bind-address=0.0.0.0"
    - name: Restart mysql
      service:
        name: mysql
        state: restarted

