---
    - name: install Java
      yum:
        name: java-11-openjdk
        state: present
    - name: install git
      yum:
        name: git
        state: present
    - name: install wget
      yum:
        name: wget
        state: present
    - name: add jenkins repo
      shell: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    - name: update jenkins
      shell: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name: update yum
      yum:
        update_cache: yes
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
      tags:
        - jenkins
    - name: Copy jenkins conf
      copy:
        src: /home/user/jenkins-conf.tar.gz
        dest: /mnt/jenkins/jenkins-conf.tar.gz
    - name: Copy jenkins home
      copy:
        src: /home/user/jenkins-home.tar.gz
        dest: /mnt/jenkins/jenkins-home.tar.gz
    - name: Stop Jenkins service
      service:
        name: jenkins
        state: stopped
    - name: Remove existing Jenkins home directory
      file:
        path: /var/lib/jenkins/home
        state: absent
    - name: Extract Jenkins home directory from backup
      shell: tar xzf /mnt/jenkins/jenkins-home.tar.gz -C /
    - name: Remove existing Jenkins configuration files
      file:
        path: /etc/default/jenkins
        state: absent
      file:
        path: /etc/sysconfig/jenkins
        state: absent
      file:
        path: /etc/init.d/jenkins
        state: absent
    - name: Extract Jenkins configuration files from backup
      shell: tar xzf /mnt/jenkins/jenkins-conf.tar.gz -C /
    - name: allow firewall to 8080
      shell: firewall-cmd --zone=public --add-port=8080/tcp --permanent
    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
